// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"time"

	"github.com/google/uuid"
)

type Submission struct {
	SubmissionID uuid.UUID `json:"submission_id"`
	AssignmentID string    `json:"assignment_id"`
	AuthorID     string    `json:"author_id"`
	CreatedAt    time.Time `json:"created_at"`
}
