// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (Submission, error)
	GetSubmissionByID(ctx context.Context, submissionID uuid.UUID) (Submission, error)
	GetSubmissionsByAssignmentID(ctx context.Context, assignmentID string) ([]Submission, error)
	GetSubmissionsByAuthorID(ctx context.Context, authorID string) ([]Submission, error)
}

var _ Querier = (*Queries)(nil)
