// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: submissions.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const createSubmission = `-- name: CreateSubmission :one
INSERT INTO submissions (assignment_id, author_id)
VALUES ($1, $2)
RETURNING submission_id, assignment_id, author_id, created_at
`

type CreateSubmissionParams struct {
	AssignmentID string `json:"assignment_id"`
	AuthorID     string `json:"author_id"`
}

func (q *Queries) CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (Submission, error) {
	row := q.db.QueryRow(ctx, createSubmission, arg.AssignmentID, arg.AuthorID)
	var i Submission
	err := row.Scan(
		&i.SubmissionID,
		&i.AssignmentID,
		&i.AuthorID,
		&i.CreatedAt,
	)
	return i, err
}

const getSubmissionByID = `-- name: GetSubmissionByID :one
SELECT submission_id, assignment_id, author_id, created_at FROM submissions
WHERE submission_id = $1
`

func (q *Queries) GetSubmissionByID(ctx context.Context, submissionID uuid.UUID) (Submission, error) {
	row := q.db.QueryRow(ctx, getSubmissionByID, submissionID)
	var i Submission
	err := row.Scan(
		&i.SubmissionID,
		&i.AssignmentID,
		&i.AuthorID,
		&i.CreatedAt,
	)
	return i, err
}

const getSubmissionsByAssignmentID = `-- name: GetSubmissionsByAssignmentID :many
SELECT submission_id, assignment_id, author_id, created_at FROM submissions
WHERE assignment_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetSubmissionsByAssignmentID(ctx context.Context, assignmentID string) ([]Submission, error) {
	rows, err := q.db.Query(ctx, getSubmissionsByAssignmentID, assignmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Submission
	for rows.Next() {
		var i Submission
		if err := rows.Scan(
			&i.SubmissionID,
			&i.AssignmentID,
			&i.AuthorID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubmissionsByAuthorID = `-- name: GetSubmissionsByAuthorID :many
SELECT submission_id, assignment_id, author_id, created_at FROM submissions
WHERE author_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetSubmissionsByAuthorID(ctx context.Context, authorID string) ([]Submission, error) {
	rows, err := q.db.Query(ctx, getSubmissionsByAuthorID, authorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Submission
	for rows.Next() {
		var i Submission
		if err := rows.Scan(
			&i.SubmissionID,
			&i.AssignmentID,
			&i.AuthorID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
